apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-app.fullname" . }}
  labels:
    app: {{ include "backend-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend-app.name" . }}
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c' ]
          args:
            - >
              until nc -z backend-mysql 3306;
              do
                echo waiting for MySQL...;
                sleep 2;
              done;
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | default "default" }}
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | default "mysql-service" }}
            - name: DATABASE_USER
              value: {{ .Values.env.DATABASE_USER | default "root" }}
            - name: DATABASE_PASS
              value: {{ .Values.env.DATABASE_PASS | default "" }}
          ports:
            - containerPort: 8089
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

