apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-app.fullname" . }}-svc
  labels:
    app: {{ include "backend-app.name" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/tpfoyer/actuator/prometheus"
    prometheus.io/port: "8089"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8089
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "backend-app.name" . }}
